---
title: Diagrama de classes FrontEnd Prototip 1
---
classDiagram

class ClientView {
    +inputUsername(): void
    +showUserInfo(user: User): void
}

class ClientDAOUser {
    +getUserByUsername(username: String): User
}

class User {
    -username: String
    -email: String
    -age: int
    +getDetails(): String
}

class Error {
    +int code 
    +String description

}

ClientView --> ClientDAOUser : Envia dades username
ClientDAOUser --> User : Petició HTTP GET username
User --> ClientDAOUser : Resposta HTTP amb JSON user if exists
ClientDAOUser --> ClientView : Dades processades
