flowchart TD
    %% Inici (Benvinguda)
    A[Vista de Benvinguda] -->|Clica Login| B[Vista de Login]
    A -->|Clica Registre| C[Vista de Registre]

    %% Login
    B -->|Introdueix email/usuari i password| D[Validació d'usuari]
    D -->|Si té 2FA activat| E[Introdueix codi 2FA]
     %%2F autentificació en dos passos per assegurar-se també al entrar a l'aplicació 
     %%i es una persona despistada amb les contrasenyes com jo
    E -->|Confirma codi| F[Accés concedit]
    D -->|Credencials incorrectes| G[Mostra missatge d'error]
    B -->|Clica 'Has oblidat la contrasenya?'| H[Recuperació de contrasenya]

    %% Registre
    C -->|Omple formulari de registre| I[Confirmació de registre]

    %% Accés a l'aplicació com a cuidador
    F -->|Usuari cuidador| J[Vista Cuidador]
    J -->|Visualitza nen/s vinculats| K[Llista d'infants]
    K -->|Selecciona un infant| L[Vista de l'Infant]
